---
profiles::alerting::alertmanager: true
profiles::alerting::alertmanager::global:
  smtp_smarthost: 'localhost:1025'
  smtp_from: 'alertmanager@localhost'
profiles::alerting::alertmanager::install_method: url
profiles::alerting::alertmanager::receivers :
  - name: Admin
    email_configs:
     - to: 'root@localhost'
       require_tls: false
profiles::mail::mailhog: true
profiles::mail::mailhog::install_method: wget
profiles::mail::mailhog::wget_source: 'https://github.com/mailhog/MailHog/releases/download/v0.2.1/MailHog_linux_amd64'
profiles::monitoring::prometheus: true
profiles::monitoring::prometheus::server: true
profiles::website::nginx: true
profiles::website::nginx::vhosts:
  prometheus.metrics.vagrant:
    proxy:  'http://127.0.0.1:9090'
